#
# ============================================================================
# Copyright (C) 2006-2018 Talend Inc. - www.talend.com
#
# This source code is available under agreement available at
# https://github.com/Talend/data-prep/blob/master/LICENSE
#
# You should have received a copy of the agreement
# along with this program; if not, write to Talend SA
# 9 rue Pages 92150 Suresnes, France
#
# ============================================================================
#

spring:
  application:
    name: dataprep-dataset-proxy

server:
  port: 8082

dataset:
  type: catalog
  url: http://localhost:3000

---
spring:
  profiles: legacy

dataset:
  type: legacy
  url: http://localhost:8080
